### ISSUE TITLE
Kinetic Release

### ISSUE THREAD

**Issue by jacquelinekay** [ros-visualization/rqt_common_plugins#364] opened 2016-04-21 17:21 UTC
Can we get an initial release of rqt_common_plugins and rqt_robot_plugins for Kinetic soon?

**Comment by dirk-thomas** [comment] 2016-04-21 17:53
The `qt5` branch does not yet work correctly. Once #359 works for both Qt 4 as well as Qt 5 this repo can be released.

`rqt_robot_plugins` needs to be updated too. I haven't looked at that at all yet.

I will close this since it is basically a duplicate of #359.

**Closed by dirk-thomas** 2016-04-21 17:53 UTC
Labels: duplicate
