### ISSUE TITLE
rqt_graph missing svg module in kinetic/Kenial

### ISSUE THREAD

**Issue by kengregson** [ros-visualization/rqt_common_plugins#374] opened 2016-05-12 01:41 UTC
May want to add/list python-pyqt5.qtsvg as a dependency

Synopsis:
# Missing dependency for rqt_graph (and friends)
> rosrun rqt_graph rqt_graph
# ImportError: No module named QtSvg

Solution:
> apt-get install python-pyqt5.qtsvg

**Comment by dirk-thomas** [comment] 2016-05-12 06:58
Duplicate of ros-visualization/rqt#107. The problem has been address in python_qt_binding 0.3.1-2. The version is currently in shadow-fixed and will be synced to the public repo soon.

**Closed by dirk-thomas** 2016-05-12 06:58 UTC
