### ISSUE TITLE
rqt_bag: parse plugin xml not found

### ISSUE THREAD

**Issue by nickoe** [ros-visualization/rqt_common_plugins#288] opened 2014-11-11 10:38 UTC
When I start rqt_bag I get an error and a segfault as below:
```
RosPluginProvider._parse_plugin_xml() plugin file "/opt/ros/indigo/share/rqt_robot_monitor/bag_plugin.xml" in package "rqt_robot_monitor" not found
Segmentation fault (core dumped)
```
See https://gist.github.com/nickoe/5b68df0a075328614eee for further details.
I am using indigo with rqt_bag 0.3.10 on archlinux. I do have rqt_robot_monitor 0.4.0 installed also.  The packager said that is seems to be an upstream problem and not a packaging problem, hence this issue report.
Please request more information if needed.

**Comment by v01d** [comment] 2015-02-02 01:16
whats the status on this? I still get a segfault on rqt_bag opening

**Comment by dirk-thomas** [comment] 2015-02-02 18:16
@v01d What version of the code are you running? The Debian package or the latest sources from rqt_common_plguins and rqt_robot_plugins?

**Comment by v01d** [comment] 2015-02-03 13:43
I have 3.10.0, on Archlinux

**Comment by dirk-thomas** [comment] 2015-02-03 17:16
Since neither of the two repositories have been released since the patched have been committed the problem is the same if you use the latest release.

Can you please try the latest versions from the repository from source and comment if you still have the same problem.

**Comment by v01d** [comment] 2015-02-06 16:15
I've downloaded latest sources and I'm still getting the segmentation fault.

**Comment by dirk-thomas** [comment] 2015-02-06 16:43
@v01d Can you please also post a stacktrace of the problem (as @bchretien did some time ago).

**Comment by v01d** [comment] 2015-02-06 16:44
To be honest I don't have time at the moment to do so. I wanted mainly to
confirm that this is still ongoing or not.
Sorry!

**Comment by v01d** [comment] 2015-02-07 15:59
Hi, I received some updates on archlinux, particularly python2-pillow 2.7
and decided to recompile rqt_bag and rqt_bag_plugins. I does not segfault
anymore.

**Comment by ablasdel** [comment] 2015-04-30 00:13
It sounds like this is fixed so I am closing it. If this is incorrect please comment and re-open

**Closed by ablasdel** 2015-04-30 00:13 UTC
Labels: bug
