### ISSUE TITLE
rqt_bag publishes wrong topic after scrolling

### ISSUE THREAD

**Issue by Daniel-Eckert** [ros-visualization/rqt_common_plugins#320] opened 2015-05-12 14:06 UTC
If I right click and publish in rqt_bag, everything works fine as long as I scroll to the top of the topic list. As soon as I scroll down, a different topic than the one I actually click on is published. It's like the scrolling works visually, but if I click on a topic it always takes the one that would have been there if I never scrolled down.
Operating system is Ubuntu 14.04.

**Comment by ablasdel** [comment] 2015-05-12 15:49
Are you saying you pause the playback and scroll and then restart play and it changes the publisher? or just scrolling causes publishers to go crazy?

Please list the steps I need to take to reproduce.

**Comment by stuglaser** [comment] 2015-05-12 20:44
I've seen this too.

When you scroll the list of topics, the right click is associated with the incorrect topic.  Instead of publishing or showing the topic under the mouse, it publishes or shows whatever topic was in that location when the scrollbar is at the top.

To reproduce:
- Run rqt_bag on a bag where the number of topics is larger than the window
- Scroll down the topics list
- Right click on a topic and try to view it
- The wrong topic shows up

I expect that rqt_bag fails to take into account scrolling when determining which topic is under the mouse cursor.

**Comment by ablasdel** [comment] 2015-05-12 21:09
Looks like the "map_y_to_topic" function doesn't take scrolling into account.

It uses the "screen Y" and instead of translating it into "Scene Y"

The function we want here is this one: http://doc.qt.io/qt-5/qgraphicsview.html#mapToScene-5

**Comment by bricerebsamen** [comment] 2015-11-17 19:12
I gave it a try. Basically calling `mapToScene` (I also tried `mapFromScene`) in this function does not do anything: `y` has same value after and before this call: `y = self.mapToScene(0, y).y()`

Maybe related: the scrollbar disappears or does not resize from time to time, the window's width needs to resized to bring it back or make it adjust. there are some notes in `_resizeEvent`.

**Comment by reinzor** [comment] 2016-04-04 11:20
What is the status of this issue"?

**Comment by guillaumeautran** [comment] 2016-04-13 15:18
I'm using version 0.3.12 of rqt_bag and are still seeing the issue. As soon as you scroll the list of topics, right click still target a different topic. 
For example, if the window shows the first 10 topics out of 20, everything works fine, however, if you scroll down, right clicking on the topic selects the topic that would have been there if you did not scroll. 
Hope this helps.

**Comment by ablasdel** [comment] 2016-04-13 15:40
@reinzor I unfortunately haven't had a chance to give this a look. If you can figure it out please go for it!

**Comment by reinzor** [comment] 2016-04-14 09:55
Submitted a quick fix as PR:

https://github.com/ros-visualization/rqt_common_plugins/pull/362

I think there should be a more pretty solution but I don't have enough knowledge about the structure at the moment.

**Comment by guillaumeautran** [comment] 2016-04-14 18:13
I'm looking at your PR reinzor. Will let you know if it works for me as well. Thanks for the prompt action here.

**Comment by guillaumeautran** [comment] 2016-04-14 18:22
@reinzor Your version has an extra 'plot' entry in the context menu 'view' submenu. Don't know what it's for but it hangs rqt_bag if selected...
As for the origin problem reported here, your fix makes it work properly. So, thanks!

**Comment by reinzor** [comment] 2016-04-14 18:30
@guillaumeautran , what do you mean with the extra 'plot' entry? I only changed the input op the map_y_to_topic function:

topic = self._timeline_frame.map_y_to_topic(self.views()[0].mapToScene(event.pos()).y())

**Comment by guillaumeautran** [comment] 2016-04-14 18:36
![screenshot from 2016-04-14 14 35 34](https://cloud.githubusercontent.com/assets/13353403/14539408/4bdf0b00-024e-11e6-82e8-f5ad66dddfc5.png)

**Comment by guillaumeautran** [comment] 2016-04-14 18:38
Definitely not related to your change but since I did not have that option in the menu before and it does seem to hang rqt_bag, I just wanted to make sure it is not a regression for a new feature...

**Comment by ablasdel** [comment] 2016-04-14 18:45
Plot has existed for awhile now. It should be acceptable to ignore it in the context of this issue. Please create another issue for plot related hanging.

This mapping looks like what should be happing with a map to scene call. I haven't had a chance to test this. Has it solved this for you guilla?

**Comment by guillaumeautran** [comment] 2016-04-14 20:11
Sounds good. Yes, your fix solves my usecase. Thanks.

**Comment by ablasdel** [comment] 2016-04-14 20:51
Fix is merged

**Closed by ablasdel** 2016-04-14 20:51 UTC
Labels: bug
